[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Don't crash when changing collabs behind the scenes
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
position = "at"
pattern = '''local swap_node = G.OVERLAY_MENU:get_UIE_by_ID('palette_selector')'''
payload = '''local swap_node = G.OVERLAY_MENU and G.OVERLAY_MENU:get_UIE_by_ID('palette_selector') or {children = {}}'''
match_indent = true